services:
  - type: web
    name: business-case-platform
    env: node
    plan: free
    buildCommand: npm run install-all
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: MONGODB_URI
        value: mongodb://localhost:27017/business-case-platform
    healthCheckPath: /api/health 